export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "surface-tint": "#494bd6",
        "on-secondary-fixed": "#131b2e",
        "tertiary-container": "#b55d00",
        secondary: "#565e74",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        tertiary: "#904900",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        surface: "#f7f9fb",
        "inverse-surface": "#2d3133",
        outline: "#767586",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed": "#07006c",
        "on-surface-variant": "#464554",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-primary": "#c0c1ff",
        error: "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#5c647a",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#ffb783",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        background: "#f7f9fb",
        primary: "#4648d4",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c7c4d7",
        "secondary-container": "#dae2fd",
        "primary-container": "#6063ee",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed": "#301400",
        "surface-container-low": "#f2f4f6",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
        "margin-page": "2rem",
        unit: "4px",
        gutter: "1.5rem",
        "container-max": "1280px",
        "stack-lg": "2rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-xs": ["Inter"],
        "label-md": ["Inter"],
        h1: ["Inter"],
        h3: ["Inter"],
        "body-base": ["Inter"],
        h2: ["Inter"],
      },
      fontSize: {
        "body-sm": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-xs": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        h1: [
          "36px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h3: [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-base": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        h2: [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
